version: "3"

services:
  db_app:
    container_name: db_app_container
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/db_app
    volumes:
      - db_app:/data/db_app
    ports:
      - "5434:5432"
    networks:
      - db_app_net
    restart: unless-stopped

networks:
  db_app_net:
    driver: bridge

volumes:
  db_app:    
