services:

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA: /data/db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_app_vol:/data/db
    networks:
      - db_app_net  
      
    restart: unless-stopped  
    container_name: c_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d opentalents"]
      interval: 5s
      timeout: 5s
      retries: 5   

networks:
  db_app_net:
    driver: bridge

volumes:
  db_app_vol:             
