services:

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA: /data/db
    volumes:
      - db_app_vol:/data/db
    networks:
      - db_app_net  
      
    restart: unless-stopped  
    container_name: ${POSTGRES_CONTAINER_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d opentalents"]
      interval: 5s
      timeout: 5s
      retries: 5   

networks:
  db_app_net:
    driver: bridge

volumes:
  db_app_vol:             
