version: "3"

services:
  db_app:
    container_name: db_app_container
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/db_app
    volumes:
      - db_app:/data/db_app
    ports:
      - "5434:5432"
    networks:
      - db_app_net
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"  
    networks:
      - db_app_net  


  webserver:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - db_app_net   

  client:
        image: nginx
        ports:
            - 800:80
        volumes:
             - ./src:/usr/share/nginx/html
  traefik:        
    image: traefik
    ports:
      - "8000:80"
      - "8080:8080"
      - "443:443"
    volumes:
    
    networks:
      - webgateway

networks:
  db_app_net:
    driver: bridge
  webgateway:
    driver: bridge
volumes:
  db_app:    
